docs: add security advisory
loopbackio/loopback.io pull request #1101
Opened 2020-11-16 18:38 UTC by raymondfeng

Signed-off-by: Raymond Feng <enjoyjava@gmail.com>

2020-11-18 19:43 UTC, emonddr requested changes

2020-11-18 19:43 UTC, emonddr commented on pages/en/sec/Security-advisory-11-20-2020.md
> +We improve JSON parsing to reject payload that contains `malicious` attributes.
```suggestion
We improved JSON parsing to reject a payload that contains `malicious` attributes.
```

2020-11-18 19:43 UTC, emonddr commented on pages/en/sec/Security-advisory-11-20-2020.md
> +You can install latest version of `@loopback/cli` and run `lb4 update` command:
```suggestion
Install the latest version of `@loopback/cli` and run the `lb4 update` command:
```

2020-12-16 17:14 UTC, dhmlau approved these changes
Thanks @jannyHou. Please rebase and squash the commits before merging.

2020-12-16 18:58 UTC, emonddr approved these changes

2020-12-18 17:01 UTC, attritionorg commented
In the advisory it includes:
 **Security risk**: High (CVSS: 7.3)

Could someone include the full CVSS string that shows the derivation of this score please?

2020-12-18 18:56 UTC, merged