feat: update LB3 LTS status
loopbackio/loopback.io pull request #1125
Opened 2021-01-01 11:14 UTC by achrinza

see https://loopback.io/doc/en/contrib/Long-term-support.html

2021-01-03 16:02 UTC, dhmlau approved these changes
@achrinza, thanks for the PR!

2021-01-12 12:00 UTC, bajtos requested changes

2021-01-12 12:00 UTC, bajtos commented on _includes/content/v3notice.html
> +their applications to LoopBack 4 as soon as possible. Learn more about
IBM will keep providing LB3 support for customers using IBM API Connect product. Let's use the following message please:

```suggestion
LoopBack 3 has reached end of life. We are no longer accepting pull requests or providing 
support for community users. The only exception is fixes for critical  bugs and security 
vulnerabilities provided as part of support for IBM API Connect customers.
We urge all LoopBack 3 users to migrate their applications to LoopBack 4 as soon as possible. 
Learn more about
```

2021-01-26 15:44 UTC, bajtos approved these changes

2021-01-26 15:45 UTC, merged

2021-01-26 15:45 UTC, bajtos commented
Landed, thank you @achrinza ❤️