Add env-based datasource config section
loopbackio/loopback.io pull request #241
Opened 2017-01-13 17:02 UTC by kjdelisle

If there's a section for this configuration already, I had great difficulty finding it.

Just adding a small bit about environment-based configuration, based on a customer question.

2017-01-13 18:02 UTC, crandmck commented
Thanks for the PR.... We do have https://loopback.io/doc/en/lb2/Environment-specific-configuration.html#data-source-configuration

I think your addition would be better placed there.  Could you please move it there?  You could leave a link in `Advanced-topics-data-sources.html` if you like.

Also, since you had a hard time finding the, I'd also suggest adding cross-references to it wherever it  makes sense.

2017-01-13 18:03 UTC, crandmck requested changes
Please see my comments above.

2017-01-13 19:30 UTC, kjdelisle commented on pages/en/lb3/Environment-specific-configuration.md
> +
Should I add that blurb about setting `export PRODUCTION=true` or `set PRODUCTION=true` here to make it clearer?

2017-01-13 19:43 UTC, crandmck commented on pages/en/lb3/Environment-specific-configuration.md
> +
Yes, I think that makes sense.

2017-01-16 23:31 UTC, merged

2017-01-16 23:32 UTC, crandmck commented
Thanks!