add more steps for m2m relations
loopbackio/loopback.io pull request #274
Opened 2017-02-07 23:40 UTC by smartmouse

connect to strongloop/loopback/issues#922 

Add more detail steps for the many to many relationship
in lb3 documentation

2017-02-08 16:44 UTC, crandmck requested changes

2017-02-08 16:44 UTC, crandmck commented on pages/en/lb3/HasManyThrough-relations.md
> +You will execute two more lb relations for the belongsTo relation
_Suggest slight rewording_:

Then, in the Physician/Patient/Appointment example, you would run the `lb relation` command twice to create the `belongsT`o relations:

2017-02-09 14:29 UTC, smartmouse reviewed
rand, please take a look, I have revised the wordings as suggested. Thanks

2017-02-09 17:39 UTC, crandmck commented
LGTM

2017-02-09 17:39 UTC, merged