Explain filter with nested property
loopbackio/loopback.io pull request #292
Opened 2017-02-21 21:10 UTC by jannyHou

Connect to https://github.com/strongloop/loopback/issues/517

Loopback support nested property filter in mongodb, memory, cloudant connectors, details seehttps://github.com/strongloop/loopback/issues/517#issuecomment-275532100

This pr explain to users about which connectors support the feature and also includes an example shows what a nested property filter looks like.

2017-02-21 21:14 UTC, jannyHou commented
@kjdelisle PTAL. Thanks.

2017-02-21 23:28 UTC, crandmck requested changes

2017-02-21 23:28 UTC, crandmck commented on pages/en/lb3/Querying-data.md
> +We currently don't support such a filter in SQL connectors.
Wording nitpick:  "Data source connectors for relational databases don't support filtering nested properties."

2017-02-21 23:28 UTC, crandmck commented on pages/en/lb3/Querying-data.md
> +Loopback supports filtering nested properties in 3 NoSQL connectors: Mongodb, Cloudant, Memory.
Please spell out "three".

2017-02-23 16:56 UTC, crandmck commented
Thx LGTM

2017-02-24 15:14 UTC, merged