Update Storage-component.md
loopbackio/loopback.io pull request #312
Opened 2017-03-07 16:09 UTC by cfjedimaster

Provides details about my recent PR to allow for unique file names.

2017-03-07 22:37 UTC, crandmck requested changes
One small formatting comment, otherwise LGTM.

2017-03-07 22:37 UTC, crandmck commented on pages/en/lb3/Storage-component.md
> +As documented above, a file uploaded with the same name as an existing file will be overwritten. By adding the configuration key `nameConflict' with the value `makeUnique`, files will automatically b
"nameConflict" needs a closing back-tick not single-quote, s/b `nameConflict`.

2017-03-07 22:51 UTC, cfjedimaster commented
Ah thanks!

2017-03-15 21:54 UTC, crandmck commented
I'll go ahead and land this, and then make the suggested fix.

2017-03-15 21:54 UTC, merged