Db creds security
loopbackio/loopback.io pull request #319
Opened 2017-03-11 00:28 UTC by crandmck

2017-03-13 10:40 UTC, ebarault commented
@crandmck : please see this comment https://github.com/strongloop/loopback/issues/3246#issuecomment-286071328

this should complement [this section](https://loopback.io/doc/en/lb3/Advanced-topics-data-sources.html)

2017-03-13 11:18 UTC, bajtos commented
`datasources.*.js` files are expected to export only the configuration of datasources, not full datasource objects.

```js
module.exports = {
  db: {
    connector: 'mongodb',
    host: 'localhost',
    port: 27017,
    database: 'mydb',
    username: process.env.MONGO_USER,
    password: process.env.MONGO_PASS
  }
};
```

However, the example is still unnecessary complex and can be greatly simplified per https://github.com/strongloop/loopback/issues/3246#issuecomment-286076113:

```js
// server/datasources.json
{
  "db": {
    "connector": "mongodb",
    "host": "localhost",
    "port": 27017,
    "database": "mydb",
    "username": "${MONGO_USER}",
    "password": "${MONGO_PASS}"
  }
}
```

IMPORTANT NOTE:

The way how datasource configurations are processed by loopback-boot, environment-specific configuration is merged with the baseline config. As a result, it's difficult to clear extra config options in environment-specific files (see e.g. https://github.com/strongloop/loopback-boot/issues/93):

```js
// datasources.json
{
  "db": {
    "connector": "mongodb",
    "database": "mydb",
    // the line below was added later by a developer
    "loggerLevel": "debug"
  }
}

// datasources.production.json
{
  "db": {
    "username": "${MONGO_USER}",
    "password": "${MONGO_PASS}"
  }
}

// oops, now we are using loggerLevel = debug in production,
// because the developer forgot to update datasources.production.json
```

To avoid the situation described above, I would personally recommend to use a connection string in production mode (see https://github.com/strongloop/loopback/issues/2089):

```js
// server/datasources.json
{
  "db": {
    "connector": "mongodb",
    "url": "${MONGODB_URL}",
    // configuration below is for Development/Test environments only
    "host": "localhost",
    "database": "my-database-name",
    // etc.
  }
}
```

2017-03-13 11:18 UTC, bajtos requested changes
☝️

2017-03-13 12:59 UTC, ebarault commented
>
```
    "username": "${MONGO_USER}",
    "password": "${MONGO_PASS}"
```

ahh, much better indeed... **thank you** for bringing this to our attention

> connection string

@bajtos in your example, why mixing both a connection string and host/database params? would the connection string if provided override the latter? (due to some implementation details)

> environment-specific configuration is merged with the baseline config

yes... this is troublesome and leads people to unexpected issues. your IMPORTANT NOTE should be somewhere in the doc (where the whole file.myenv.json/js is documented)

2017-03-13 14:52 UTC, bajtos commented
> in your example, why mixing both a connection string and host/database params? would the connection string if provided override the latter? (due to some implementation details)

Yes, connection string is overriding all other parameters, at least in the connectors maintained by us. See https://github.com/strongloop/loopback/issues/2089#issuecomment-186189300

2017-03-13 18:23 UTC, ebarault commented
thanks for clarifying

then it sort of superseeds what i understood was the best practice so far: 
> defining as many `datasource.env.json/js` files as there are environments, including development

do you consider the doc should reflect this? (mention it as best practice and keep mentioning other alternatives)

2017-03-14 16:16 UTC, crandmck commented
I'll update this PR to reflect @bajtos input above (asap--been slammed with other stuff).  I wasn't aware of this capability, and it definitely needs to be documented.

2017-03-15 22:23 UTC, crandmck commented
OK, I updated the PR with the input from @bajtos.

My apologies, I accidentally committed `pages/en/lb2/Basic-model-object.md` to this `db-creds-security` branch.  Please ignore it--It is completely unrelated to this PR and just has some formatting improvements.  I could back out the changes and recommit elsewhere, but if you don't mind ignoring, it can piggyback on this PR.... :-)

2017-03-16 18:30 UTC, crandmck commented
@bajtos @ebarault Could you please take another look.

2017-03-16 18:36 UTC, ebarault commented
@crandmck : sure, it'll try tonight or tomorrow

2017-03-16 23:16 UTC, ebarault reviewed
In addition to my inlined comments, i'd add that the accessibility of this information could be improved.
As shown below there are two sections discussing the subject: "Attaching models to datasources" and "Understanding datasources", in addition "Understanding datasources" is nested in a section named "Connecting models to datasources", which is much too close to "Attaching models to datasources".

* Defining models
** Attaching models to datasources

* Connecting models to datasources
** Understanding datasources

![image](https://cloud.githubusercontent.com/assets/12000935/24022525/516fca34-0aa7-11e7-876d-94ccefdab6ea.png)

Ideally datasources would require their own top section, and would fit just before Defining models.
The content of **Defining datasources** would be extracted from the two sub-sections Attaching models to datasources and Understanding datasources.
The **Connecting models to datasources** section's name should change. It is as of now a melting pot of advanced details and functionalities.
The applicable content would fit in a new top-level **Attached models to datasources**

So the logical sequence would look like

* Defining datasources
** Datasources: Advanced topics
* Defining models
* Attaching models to datasources

2017-03-16 23:16 UTC, ebarault commented on pages/en/lb3/Attaching-models-to-data-sources.md
> +"%}
i'd put this tip block after the /server/datasources.json example (L80). This will serve as a junction with the following section "Specifying database credentials with environment variables"

Also the display is a bit inconsistent between Advanced-topics-data-sources.md where it's a warning, and here where it's a tip.

2017-03-16 23:16 UTC, ebarault commented on pages/en/lb3/Attaching-models-to-data-sources.md
> + ```
i'd suggest providing a valid datasource config here (including a connector, a host, etc.)
shall we be consistent through the different examples regarding the datasources definition? for now we go from mysql to mongodb

2017-03-16 23:16 UTC, ebarault commented on pages/en/lb3/Attaching-models-to-data-sources.md
> +You can use different credentials for development and production by using the NODE_ENV
_Rewording suggestion (**bold** differs)_
"you can use different **datasources definitions, including** credentials by using..."

2017-03-16 23:16 UTC, ebarault commented on pages/en/lb3/Attaching-models-to-data-sources.md
> +" %}
- one typo: Loo**o**pback

- Also, this statement on how the merge between top-level file and environment files is operating and the inherent limitation should be mentioned at the top of the  **Environment-specific-configuration.html** file, shared for all applicable files, and combined with the content of the important note : "The additional files can override the top-level keys with value-types (strings, numbers) only. Nested objects and arrays are not supported." (which BTW is duplicated in the file, with two different wordings)

- The db credentials warning is missing in Environment-specific-configuration.html.

- for the record: the last example in http://loopback.io/doc/en/lb3/Environment-specific-configuration.html#data-source-configuration states a **datasources.production.json** file, but it's a **.js**

- _Rewording suggestion (**bold** differs)_
"As a result, **it might be difficult in some setups** to clear extra **datasource** settings **inherited from the top-level datasources.json file** in environment-specific files. **To ease the juggling between different datasources when switching environments it is recommended when applicable to use a single datasources.json file mixing both a individual settings such as `host`, `port`, `database` for local environment and a `url` connection string setting that will override the formers for environment such as staging and production.** See the example below."

2017-03-16 23:16 UTC, ebarault commented on pages/en/lb3/datasources.json.md
>    }
content of this file is greatly duplicated with content in Environment-specific-configuration.html#data-source-configuration, which will make the whole difficult to maintain. Hence, cross-linking would be preferable.

2017-03-16 23:52 UTC, ebarault commented
further comments:

@bajtos : does loopback-boot supports template literals in config.json?

(i could only find this in changes.md)
```
2015-08-28, Version 2.12.0
==========================
 * Resolve ${var} values in component-config.json (Hage Yaapa)
 * Resolve ${var} values in middleware.json (Hack Sparrow)
```

if so, the example in Environment-specific-configuration.html#application-wide-configuration page should be also reviewed to make use of the ${MY_ENV_VAR} ability.

As of now it's 
```
module.exports = {
  host: process.env.CUSTOM_HOST,
  port: process.env.CUSTOM_PORT
};
```
it could be a config.json file 
```
```

2017-03-17 00:06 UTC, ebarault commented on pages/en/lb3/Advanced-topics-data-sources.md
> +
ok for the warning but it stands that the problem expressed [in this comment](https://github.com/strongloop/loopback.io/pull/317#issuecomment-285854277) is still not covered by the doc.

The doc explains how to create datasource programmatically but some info should be added on where to use this snippet, and how to connect models on these datasources (programmatically I suppose, but one could assume that they could reference datasources created programmatically in the model-config.json

2017-03-17 17:40 UTC, crandmck commented
Thanks for all the input.  This is very helpful.

Re your comment

> there are two sections discussing the subject: "Attaching models to datasources" and "Understanding datasources", in addition "Understanding datasources" is nested in a section named "Connecting models to datasources", which is much too close to "Attaching models to datasources".

I totally agree, and I've been aware of this for quite a while, but I never got around to addressing it.  Now you'll guilt me into it ;-)  

But seriously, I agree we should fix this.  Unfortunately, I'm taken up with work on other projects at the moment.  However, I'll make sure it's put at the top of the queue once the other work is done.

2017-03-21 22:18 UTC, crandmck commented on pages/en/lb3/Advanced-topics-data-sources.md
> +
I opened a new issue for this: #331

2017-03-21 23:22 UTC, crandmck commented on pages/en/lb3/Attaching-models-to-data-sources.md
> +"%}
Done, and made it warning.

2017-03-21 23:22 UTC, crandmck commented on pages/en/lb3/Attaching-models-to-data-sources.md
> + ```
Done; changed all examples to MongoDB.

2017-03-21 23:22 UTC, crandmck commented on pages/en/lb3/Attaching-models-to-data-sources.md
> +You can use different credentials for development and production by using the NODE_ENV
Changed wording (didn't use your suggestion, but clarified, I hope).

2017-03-21 23:23 UTC, crandmck commented on pages/en/lb3/Attaching-models-to-data-sources.md
> +" %}
Incorporated all these suggestions.

2017-03-21 23:24 UTC, crandmck commented on pages/en/lb3/datasources.json.md
>    }
I edited `datasources.json.md` page extensively to replace a lot of the content with cross-references.  The procedural info was really inappropriate for a reference article (which it is), and is provided elsewhere, so I removed it.

2017-03-21 23:29 UTC, crandmck commented
I'd like to keep this issue focused on the original task (specifying database credentials securely).  I opened #332 for the broader task of consolidating the information that's now in a couple different places.  I do want to address this, but don't have time at the moment to do it justice.

So @ebarault if you would please review my latest changes and (hopefully) approve the PR.  I'd like to land it if possible.  We can carry on related work in #332 and #331.  Thanks again for your help.

2017-03-22 09:16 UTC, bajtos approved these changes
LGTM.

There is one claim that I think is not correct, but that can be fixed in a follow-up pull request.

2017-03-22 09:16 UTC, bajtos commented on pages/en/lb3/Attaching-models-to-data-sources.md
> +Environment-specific configurations can override the top-level values with string and number values only. You cannot use objects or array values.
This is not true - AFAIK, one can override object values with object values, array values with array values too.

2017-03-22 11:03 UTC, ebarault commented on pages/en/lb3/Attaching-models-to-data-sources.md
> +Environment-specific configurations can override the top-level values with string and number values only. You cannot use objects or array values.
well this is copy/paste from the current doc

2017-03-22 17:44 UTC, crandmck commented
> There is one claim that I think is not correct, but that can be fixed in a follow-up pull request.

OK, thanks.  I'm going to land this and open a separate issue to clear this up.

2017-03-22 17:44 UTC, merged