[WIP] Update datasource documents
loopbackio/loopback.io pull request #369
Opened 2017-04-27 21:00 UTC by loay

### Description

Update api documents/ js docs and address all REVIEW and FIXME tags
#### Related issues

connect to https://github.com/strongloop-internal/scrum-apex/issues/175

### Checklist

- [ ] New tests added or existing tests modified to cover all changes N/A
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

2017-04-27 21:34 UTC, jannyHou commented on pages/en/lb3/Attaching-models-to-data-sources.md
> +If you choose not to type the database credentials, and/or `no` for installing the database connector, then you can install it manually and edit `server/datasources.json` as in the following steps.
maybe change 'and/or'  ---> 'and'?

2017-04-27 21:37 UTC, ssh24 requested changes

2017-04-27 21:37 UTC, ssh24 commented on pages/en/lb3/Attaching-models-to-data-sources.md
> +? Select the connector for mongodb: MongoDB (supported by StrongLoop)
Change this to `Select the connector for mongo1` instead of `Select the connector for mongodb`

2017-04-27 21:49 UTC, 0candy commented on pages/en/lb3/datasources.json.md
> +To connect a model to a data source, [follow these steps](https://loopback.io/doc/en/lb2/datasources.json.html#properties-for-database-connectors)  to create a datasource.
Extra space before `to create a datasource`.

2017-04-28 02:15 UTC, dhmlau requested changes
Request changes mainly because there is one place that `"<filename>"` doesn't appear in the actual view, though it is there in the source code.

2017-04-28 02:15 UTC, dhmlau commented on pages/en/lb3/Attaching-models-to-data-sources.md
> +? Enter the model name: myModel
Might wanna add how to create model..  to run `slc loopback:model` or `apic create --type model` for API Connect (similar format as what you have in this file)

2017-04-28 02:15 UTC, dhmlau commented on pages/en/lb3/datasources.json.md
> +To see data stored in memory connector, add <code> "file": "<filename>"</code>
When i'm viewing the file (from clicking view), `"<filename>"` is gone.  You might wanna take a look. 

Suggested change: "To store data in a file for memory connector, add...."

2017-04-28 03:15 UTC, loay commented on pages/en/lb3/Attaching-models-to-data-sources.md
> +If you choose not to type the database credentials, and/or `no` for installing the database connector, then you can install it manually and edit `server/datasources.json` as in the following steps.
it is an actual `and/or` situation because the user may choose to do both manually or one of the two conditions

2017-04-28 03:19 UTC, loay commented on pages/en/lb3/Attaching-models-to-data-sources.md
> +? Enter the model name: myModel
There is actually a link for the model generator 2 lines above. I am just trying to explain to the user that you don't need to do it manually but you can attach the model using the command prompt. I am more concerned here about the model attachment.

2017-04-28 03:20 UTC, loay commented on pages/en/lb3/datasources.json.md
> +To see data stored in memory connector, add <code> "file": "<filename>"</code>
You are absolutely right. Fixing

2017-04-28 03:26 UTC, loay commented
@jannyHou @0candy @dhmlau @ssh24 PTAL .. thanks

2017-04-28 12:12 UTC, ssh24 approved these changes

2017-04-28 12:37 UTC, dhmlau approved these changes

2017-04-28 15:58 UTC, jannyHou approved these changes
LGTM

2017-04-28 16:40 UTC, crandmck commented on pages/en/lb3/Attaching-models-to-data-sources.md
> +If you choose not to type the database credentials, and/or `no` for installing the database connector, then you can install it manually and edit `server/datasources.json` as in the following steps.
Actually, I think it should be reworded like this:

If you don't have the tool install install the database connector when it prompts you , then you must install it yourself using `npm install`.  If you don't enter the database credentials when prompted, then you must add them manually to `server/datasources.json` as shown below.

2017-04-28 16:49 UTC, crandmck requested changes

2017-04-28 16:49 UTC, crandmck commented on pages/en/lb3/Create-new-data-source.md
> +
Same rewording as above.

2017-04-28 16:49 UTC, crandmck commented on pages/en/lb3/datasources.json.md
> +To store data in a file for memory connector, add <code> "file": <i>"file_name"</i></code>
> To make the memory connector store data in a file so it persists beyond application restarts, add ... 

Add period at end of sentence.

Add cross-ref:
For more information see [Memory connector - data persistence](Memory-connector.html#data-persistence).

2017-04-28 17:17 UTC, loay commented
@crandmck FIxed. PTAL again. Thanks.

2017-04-28 17:26 UTC, crandmck commented
Just a couple typos. Other than that, LGTM.

2017-04-28 17:57 UTC, crandmck approved these changes

2017-04-28 17:57 UTC, crandmck commented on pages/en/lb3/Attaching-models-to-data-sources.md
> +If you don't have the tool install to install the database connector when it prompts you , then you must install it yourself using `npm install`. If you do not enter the database credentials when pro
Typo:
> If you don't have the tool install to install ...

2017-04-28 17:57 UTC, crandmck commented on pages/en/lb3/Create-new-data-source.md
> +If you don't have the tool install to install the database connector when it prompts you , then you must install it yourself using npm install. If you don't enter the database credentials when prompt
Same typo
> If you don't have the tool install to install ...

2017-04-28 17:59 UTC, merged