[WIP] Update datasource documents LB2
loopbackio/loopback.io pull request #371
Opened 2017-04-27 21:46 UTC by ssh24

### Description

Update api documents/ js docs and address all REVIEW and FIXME tags
#### Related issues

connect to https://github.com/strongloop-internal/scrum-apex/issues/175

### Checklist

- [ ] New tests added or existing tests modified to cover all changes N/A
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

2017-04-27 21:50 UTC, 0candy approved these changes

2017-04-28 02:06 UTC, dhmlau approved these changes
LGTM 
you might wanna address my comment.

2017-04-28 02:06 UTC, dhmlau commented on pages/en/lb2/Attaching-models-to-data-sources.md
> +```shell
might wanna add something like:
to create a model, run `slc loopback:model` or `apic create --type model` (in similar format you have above)

2017-04-28 17:00 UTC, crandmck commented
Please make changes here corresponding to the requested changes for LB3 in #369.

2017-04-28 17:00 UTC, crandmck requested changes

2017-04-28 17:00 UTC, crandmck commented on pages/en/lb2/datasources.json.md
> +    This adds the new data source to `server/datasources.json` which can be later used to update the config if needed.
We use terminology "data source properties" not "config/configuration" or "settings".  Technically, they are for the data source (i.e. this instance), not the connector (the `loopback-connector-*` package).

> Follow the prompts to fill in the connector configurations.

Change to:
"Respond to the prompts to set data source properties such as database credentials."

> ... which can be later used to update the config if needed

Change to:

"To change the data source properties, edit this file."

2017-04-28 18:47 UTC, crandmck approved these changes

2017-04-28 18:52 UTC, merged