docs(boot): Docs for @loopback/boot
loopbackio/loopback.io pull request #631
Opened 2018-02-21 06:56 UTC by virkt25

Documentation explaining the `@loopback/boot` extension and the various aspects that make it up.

Need a review and suggestions on the following:
-- Should individual Booters be documented here? (Or link to docs in README for the package?)
-- Layout?
-- Grammar?

2018-02-22 15:00 UTC, dhmlau reviewed
While this doc might have good information on what boot is and how it works, I might miss the points (as a user):
- why do i need to care about how boot if artifacts are automatically loaded for me when using CLI
- in what case i need to know more about booters

2018-02-22 15:00 UTC, dhmlau commented on pages/en/lb4/Booting-an-Application.md
> +discover and bind artifacts, all packaged in an easy to use Mixin.
"easy to use" => "easy-to-use"?

2018-02-22 15:00 UTC, dhmlau commented on pages/en/lb4/Booting-an-Application.md
> +artifact describes Controllers, Repositories, Models, etc.
Suggestion to reword the 2nd sentence:
LoopBack constructs include Controllers, Repositories.....

2018-02-22 15:00 UTC, dhmlau commented on pages/en/lb4/Booting-an-Application.md
> +classes to this method and they will all get bound to the Application using the
get bound => get bounded

2018-02-22 15:00 UTC, dhmlau commented on pages/en/lb4/Booting-an-Application.md
> +This component is added to a Application by `BootMixin` if used. The Component:
"a Application" => "an Application"? 
"The Component" => "This Component"

2018-02-22 15:00 UTC, dhmlau commented on pages/en/lb4/Booting-an-Application.md
> +bound to an Application as a `SINGLETON`. The Bootstrapper class provides a `boot()`
bound -> bounded

2018-02-22 15:00 UTC, dhmlau commented on pages/en/lb4/Booting-an-Application.md
> +Each call of the `boot()` method creates a new `Context` that sets the `app` context
suggestion:
"Each call of the `boot()` method" => "Each `boot()` method call"

2018-02-22 15:00 UTC, dhmlau commented on pages/en/lb4/Booting-an-Application.md
> +as it's parent. This is done so each `Context` for `boot` gets a new instance of
it's parent => its parent

2018-02-22 15:04 UTC, dhmlau commented on pages/en/lb4/Booting-an-Application.md
> +New projects generated using `@loopback/cli` or `lb4` are automatically enabled
I wonder if it's a good idea to let the readers know up front that for general use, artifacts are automatically loaded for you and you don't need to know too much details.

2018-02-22 15:56 UTC, shimks reviewed
Nice docs. It's missing a sidebar entry and there are some minor nitpicks, but once that's been taken care of, LGTM.

2018-02-22 15:56 UTC, shimks commented on pages/en/lb4/Booting-an-Application.md
> +to infer types and avoid errors. \_If using `tslint` with the `no-unused-variable` rule,
`\_`

2018-02-22 15:56 UTC, shimks commented on pages/en/lb4/Concepts.md
> +* [**Booting an Application**](Booting-an-Application.html): A convention based
I think the section on `boot` should be somewhere at the bottom if the order matters. Most users of LoopBack won't really have to know about the fine details of booters other than that they do context bindings for you. I think it'd be more appropriate below `Context` here.

2018-02-22 15:56 UTC, shimks commented on pages/en/lb4/Booting-an-Application.md
> +* Process those artifacts automatically (this usually means binding them to the Application)
I think we should use fit in the concept of `context` in here somewhere, just to make sure that users understand that `boot` takes care of automatic **`context`** bindings.

2018-02-23 05:20 UTC, virkt25 commented on pages/en/lb4/Booting-an-Application.md
> +classes to this method and they will all get bound to the Application using the
Is `be bound` better?

2018-02-23 05:36 UTC, virkt25 commented
@dhmlau Good points! Thoughts on splitting this doc into 2 different pages? 
- One for "users" of the Application (all they need to know is CLI projects are enables, how to add to manual application and the config options avaiable to them) 
- Another for Extension Developers who would have more of an interest in understanding how `@loopback/boot` works and how they can leverage this knowledge to write their own `Booter` -- realistically I think an extension developer just needs to know how to write a Booter which doesn't require details about the inner workings

Does anyone need to know how Boot works under the hood?

2018-02-23 14:17 UTC, dhmlau commented
+1 on splitting into 2 pages or at least 2 sections. 
I wonder if the split is MVP.  But the other argument is we might as well get it all fixed at one time, rather than going back again when we have time.

2018-02-23 19:36 UTC, kjdelisle requested changes
Excellent overall, just has some minor spelling, grammar and phrasing problems to address and then it can land.

2018-02-23 19:36 UTC, kjdelisle commented on pages/en/lb4/Booting-an-Application.md
> +_Tip_: `application.ts` will likely be at the root of your project, so it's path can be
`it's` -> `its`

2018-02-23 19:36 UTC, kjdelisle commented on pages/en/lb4/Booting-an-Application.md
> +Since this is a convention based Bootstrapper, it is important to set a `projectRoot`,
`convention-based`

2018-02-23 19:36 UTC, kjdelisle commented on pages/en/lb4/Booting-an-Application.md
> +Application and calls it's `boot` function. This should be called before an
`it's` -> `its`

2018-02-23 19:36 UTC, kjdelisle commented on pages/en/lb4/Booting-an-Application.md
> +A convenience method manually bind `Booters`. You can pass any number of `Booter`
`A convenience method to manually bind...`

2018-02-23 19:36 UTC, kjdelisle commented on pages/en/lb4/Booting-an-Application.md
> +classes to this method and they will all get bounded to the Application using the
`..and they will all be bound...`

2018-02-23 19:36 UTC, kjdelisle commented on pages/en/lb4/Booting-an-Application.md
> +A Class that acts as the "manager" for Booters. The Boostrapper is designed to be
`Boostrapper` -> `Bootstrapper`

:P

2018-02-23 19:36 UTC, kjdelisle commented on pages/en/lb4/Booting-an-Application.md
> +bounded to an Application as a `SINGLETON`. The Bootstrapper class provides a `boot()`
`bounded` -> `bound`

2018-02-23 19:36 UTC, kjdelisle commented on pages/en/lb4/Booting-an-Application.md
> +The boostrapper can be configured to run only certain booters or phases of booters
`boostrapper` -> `bootstrapper`

2018-02-23 19:36 UTC, kjdelisle commented on pages/en/lb4/Booting-an-Application.md
> +The boostrapper can be configured to run only certain booters or phases of booters
I'd also rephrase it a bit: `...can be configured to run specific booters, or boot phases...`

2018-02-23 19:36 UTC, kjdelisle commented on pages/en/lb4/Booting-an-Application.md
> +To use `BootExecOptions` you must directly call `bootstrapper.boot()` instead of `app.boot()`.
Need a comma after `BootExecOptions`.

"To use BootExecOptions, you must..."
(I can't use the backticks in the example, messes up the formatting.)

2018-02-23 19:36 UTC, kjdelisle commented on pages/en/lb4/Concepts.md
> +* [**Booting an Application**](Booting-an-Application.html): A convention based
`convention-based`

2018-02-23 21:26 UTC, dhmlau commented
> +1 on splitting into 2 pages or at least 2 sections.
I wonder if the split is MVP. But the other argument is we might as well get it all fixed at one time, rather than going back again when we have time.

Please feel free to create separate issue to track that.  I don't think it should be a blocker to land this PR.

2018-02-27 16:33 UTC, b-admike commented on pages/en/lb4/Booting-an-Application.md
> +Used to configure the `Booter` with it's default options.
`it's` -> `its`

2018-02-27 16:33 UTC, b-admike commented on pages/en/lb4/Booting-an-Application.md
> +class MyApp extends BootMixin(Application) {}
can we show the imports here?

2018-02-27 16:46 UTC, shimks approved these changes
Some tables are broken, but once that's been fixed, :shipit:

2018-02-27 16:46 UTC, shimks commented on pages/en/lb4/Booting-an-Application.md
> +| `dirs`       | `string | string[]` | `['controllers']`    | Paths relative to projectRoot to look in for Controller artifacts                                             |
The table is broken here

2018-02-27 16:46 UTC, shimks commented on pages/en/lb4/Booting-an-Application.md
> +| `dirs`       | `string | string[]` | `['repositories']`   | Paths relative to projectRoot to look in for Repository artifacts                                             |
Broken here as well

2018-02-27 16:47 UTC, b-admike approved these changes
+1 for Kyu's comments, LGTM otherwise

2018-02-27 21:55 UTC, bschrammIBM approved these changes

2018-02-28 05:42 UTC, virkt25 commented
Good catch @shimks. Used `|` in the table without escaping it. Weird that the backticks don't escape it automatically.

2018-02-28 15:07 UTC, kjdelisle approved these changes

2018-02-28 15:31 UTC, merged