Routes wont allow further middlewares to be executed
loopbackio/loopback.io pull request #828
Opened 2019-03-29 09:16 UTC by lespacedunmatin

Documenting issue #1232 : 
> @bajtos said:
> Routes don't call `next`, therefore your middleware is never executed by express.

2019-03-29 12:58 UTC, bajtos requested changes
Thank you @lespacedunmatin for the pull request, I appreciate your effort to improve our documentation ❤️

2019-03-29 12:58 UTC, bajtos commented on pages/en/lb3/Defining-middleware.md
> +**Note**: If a route is found in the `route` phase, no middlewares after that will be called within loopback, including `route:after`. This is due to the express behavior.
I find the proposed text possibly misleading.

- This behavior is not specific for `route` phase, it applies to all middleware independently on where it is registered. For example, `cors` middleware can handle `OPTIONS` request and terminate the middleware chain early on.
- The behavior kicks in when a middleware or a route does not call `next()`. 
- Routes created for LoopBack remote methods never call `next()`.
- Express routes serving content typically don't call `next` either.
- By default, strong-remoting will "own" the URL namespace (typically all paths starting with `/api`). When there is no remote method matching the requested path + verb, then 404 error is triggered. This behavior can be disabled via `rest.handleUnknownPaths` in `server/config.json`, see [Remoting properties](https://loopback.io/doc/en/lb3/config.json.html#remoting-properties)

2019-09-10 22:13 UTC, dhmlau commented
@lespacedunmatin, could you please address the comment from @bajtos ? Thanks.

2019-09-10 22:14 UTC, dhmlau commented
Also, could you please fix the commit message?  Here is our commit message guideline: https://loopback.io/doc/en/contrib/git-commit-messages.html

2019-09-10 22:15 UTC, dhmlau commented
Also, could you please fix the commit message?  Here is our commit message guideline: https://loopback.io/doc/en/contrib/git-commit-messages.html

2019-09-10 22:15 UTC, dhmlau commented
@slnode test please

2020-03-27 08:37 UTC, closed without merging